services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web1
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1"]
      interval: 30s
      timeout: 10s
      retries: 3
