services:
  mongodb_test:
    image: mongo:latest
    container_name: mongodb_test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data_test:/data/db

volumes:
  mongodb_data_test:
