export enum TriggerTypeEnum {
  STRESS = 'Stress',
  LACK_OF_SLEEP = 'Lack of Sleep',
  FOOD = 'Food',
  WEATHER = 'Weather',
  EXERCISE = 'Exercise',
  MEDICATION = 'Medication',
  SUNLIGHT = 'Sun light',
  SMELL = 'Smell',
  LOUD_PLACE = 'Loud Place',
  TRAVEL = 'Travel',
  HEALTH_PROCEDURE = 'Health Procedure',
  FLU = 'Flu',
  MAGNETIC = 'Magnetic',
  UNHYDRATED = 'Unhydrated',
  HANGOVER = 'Hangover',
  ALCOHOL = 'Alcohol',
  PARTY = 'Party',
  FATIGUE = 'Fatigue',
  HARD_JOB = 'Hard Job',
  COLD = 'Cold',
  TOOTHACHE = 'Toothache',
  STOMACH = 'Stomach',
  TIRED = 'Tired',
  CHOCOLATE = 'Chocolate',
}
