name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.test.yml"
          down-flags: "--volumes"
        env:
          NODE_ENV: "test"
          MONGO_INITDB_ROOT_USERNAME: "root"
          MONGO_INITDB_ROOT_PASSWORD: "example"

      - name: Wait for MongoDB container to be ready
        run: |
          echo "Waiting for MongoDB container to be ready..."
          max_retries=10
          retry_count=0
          until nc -z localhost 27018 || [ $retry_count -eq $max_retries ]; do
            echo "Attempt $retry_count: MongoDB is not yet available. Waiting..."
            sleep 5
            retry_count=$((retry_count+1))
          done
          
          if [ $retry_count -eq $max_retries ]; then
            echo "Timed out waiting for MongoDB to start."
            exit 1
          fi
          echo "MongoDB container is ready."

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      - name: Test
        run: pnpm test
        env:
          NODE_ENV: test
          IS_PODMAN: false
          DATABASE_URI: mongodb://root:example@localhost:27018/test_db_name?authSource=admin

      - name: Test E2E
        run: pnpm test:e2e
        env:
          NODE_ENV: test