name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Setting an environment variable with the value of a configuration variable
  mongodb_user: ${{ vars.MONGODB_USER }}
  mongodb_host: ${{ vars.MONGODB_HOST }}
  mongodb_cluster: ${{ vars.MONGODB_CLUSTER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      - name: Test
        run: NODE_ENV=test pnpm test
        env:
          NODE_ENV: test
          IS_PODMAN: false
          MONGODB_USER: ${{ env.mongodb_user }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_HOST: ${{ env.mongodb_host }}
          MONGODB_CLUSTER: ${{ env.mongodb_cluster }}

      - name: Test E2E
        run: NODE_ENV=test pnpm test:e2e
        env:
          NODE_ENV: test